[tool.ruff]
line-length = 110
# Enable Pyflakes `E` and `F` codes by default.
select = [
    "F", "E", "C90", "I", "UP", "N", "B", "A", "C4", "RET", "SIM", "TID",
]
ignore = [
    "UP008", "E741", "B023", "N802", "A003", "B904", "N806", "RET504", "RET506",
    "B008", "B905", "UP006", "UP007", "RET502", "RET503", "TID252"
]

# Always autofix, but never try to fix `F401` (unused imports).
fix = true
unfixable = []
per-file-ignores = {"__manifest__.py" = ["B018"], "__init__.py" = ["F401"]}

# Excl